import { Roboto } from "next/font/google";
import "./globals.css";
import MuiProvider from "../components/MuiProvider/MuiProvider";
import QuizProvider from "./context/QuizSessionContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/context/AuthContext";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Skill Conquest",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${roboto.variable}`}>
        <AuthProvider>
          <QuizProvider>
            <MuiProvider>{children}</MuiProvider>
            <ToastContainer />
          </QuizProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
