import {
    generateNaturalWholeNumbers,
    generateIntegers,
    generateFractions,
    generateDecimals,
    generateLCM,
    generateHCF,
    generateRatioProportion,
    generateSquareRoots,
    generateCubeRoots,
    generateExponents,
    generateBODMAS,
    generateAlgebraicAdditionSubtraction,
    generateAlgebraicMultiplication,
    generateAlgebraicDivision,
    generateLinearEquationOneVar,
    generateSimultaneousEquations,
    generateQuadraticEquation,
    generatePerimeter,
    generateArea,
    generateCartesianPoint,
    generateCoordinateGeometry,
    generateSectionFormula,
    generateTrigonometry,
    generateTrigRatios,
    generatePythagoras,
    generateClocks,
    generateProbability,
    generateWordProblemLinearEq,
    generateWordProblem,
    generateMiscellaneous
} from './grade10Generators.mjs';

const generate = (generator, count = 10) => {
    return Array.from({ length: count }, () => generator());
};

const Grade10Questions = {
    q1: generate(generateNaturalWholeNumbers),
    q2: generate(generateIntegers),
    q3: generate(generateFractions),
    q4: generate(generateDecimals),
    q5: generate(generateLCM),
    q6: generate(generateHCF),
    q7: generate(generateRatioProportion),
    q8: generate(generateSquareRoots),
    q9: generate(generateCubeRoots),
    q10: generate(generateExponents),
    q11: generate(generateBODMAS),
    q12: generate(generateAlgebraicAdditionSubtraction),
    q13: generate(generateAlgebraicMultiplication),
    q14: generate(generateAlgebraicDivision),
    q15: generate(generateLinearEquationOneVar),
    q16: generate(generateSimultaneousEquations),
    q17: generate(generateQuadraticEquation),
    q18: generate(generatePerimeter),
    q19: generate(generateArea),
    q20: generate(generateCartesianPoint),
    q21: generate(generateCoordinateGeometry),
    q22: generate(generateSectionFormula),
    q23: generate(generateTrigonometry),
    q24: generate(generateTrigRatios),
    q25: generate(generatePythagoras),
    q26: generate(generateClocks),
    q27: generate(generateProbability),
    q28: generate(generateWordProblemLinearEq),
    q29: generate(generateWordProblem),
    q30: generate(generateMiscellaneous)
};

export default Grade10Questions;
